= Bookbag Content Container Image

== Overview

This repository provides the logic to build an Antora courseware repository into a container image that can be used with just Docker/Podman or on top of OpenShift.

== Usage

. Create a new content repository and publish it at a public Github compatible URL. See below for content repository requirements.
. Create a new container image
+
[source,sh]
----
# Clone this repo first
cd $HOME
git clone https://github.com/wkulhanek/bookbag-content
cd $HOME/bookbag-content

# Location of the Content Repository
ANTORA_SOURCE=https://github.com/wkulhanek/bookbag-rhtr2020
# Branch to checkout of the Content Repository
ANTORA_BRANCH=main

# Build the container image using podman
podman build --build-arg ANTORA_SOURCE=$ANTORA_SOURCE --build-arg ANTORA_BRANCH=$ANTORA_BRANCH -t wkulhanek/bookbag-content:latest .

# Or build the container image using Docker if podman is not available (e.g. on MacOS)
docker build --build-arg ANTORA_SOURCE=$ANTORA_SOURCE --build-arg ANTORA_BRANCH=$ANTORA_BRANCH -t wkulhanek/bookbag-content:latest .
----

. Environment variables can be either passed individually or aggregated into one variable containing a JSON array.
.. For individual variables run the image passing any environment variables as necessary.
+
[source,sh]
----
guid=wkosp
ocp_username=wkulhane-redhat.com
jenkins_url=https://homework-jenkins-gpte-jenkins.apps.shared-na4.na4.openshift.opentlc.com
gitea_url=https://homework-gitea.apps.shared-na4.na4.openshift.opentlc.com
login_command='oc login -u wkulhane-redhat.com -p <Your OpenTLC password> https://api.shared-na4.na4.openshift.opentlc.com:8443'
docker run --name bookbag \
           --rm --publish 8080:8080 \
           --env guid="$guid" --env ocp_username="$ocp_username" \
           --env jenkins_url="$jenkins_url" --env gitea_url="$gitea_url" \
           --env login_command="${login_command}" \
       wkulhanek/bookbag-content:latest
----

.. For aggregated JSON run the image passing one variable *WORKSHOP_VARS* containing a JSON array of variables.
+
[source,sh]
----
WORKSHOP_VARS='{"guid": "wkosp", "ocp_username": "wkulhane-redhat.com", "jenkins_url": "https://homework-jenkins-gpte-jenkins.apps.shared-na4.na4.openshift.opentlc.com", "gitea_url": "https://homework-gitea.apps.shared-na4.na4.openshift.opentlc.com", "login_command": "oc login -u wkulhane-redhat.com -p <Your OpenTLC password> https://api.shared-na4.na4.openshift.opentlc.com:8443"}'

docker run --name bookbag \
           --rm --publish 8080:8080 \
           --env WORKSHOP_VARS="$WORKSHOP_VARS"
       wkulhanek/bookbag-content:latest
----

. Access http://localhost:8080 to test your documentation.

== Deploy to OpenShift Container Platform

. Log into your OpenShift cluster
. Create a new project
+
[source,sh]
----
oc new-project bookbag
----

. Create a new Build Configuration
+
[source,sh]
----
# Location of the Content Repository
ANTORA_SOURCE=https://github.com/wkulhanek/bookbag-rhtr2020
# Branch to checkout of the Content Repository
ANTORA_BRANCH=main

oc new-build --name bookbag --strategy=docker https://github.com/wkulhanek/bookbag-content --build-arg ANTORA_SOURCE=${ANTORA_SOURCE} --build-arg ANTORA_BRANCH=${ANTORA_BRANCH}
----

. Once the build completes create a new Deployment using the created container image.
+
Environment variables can be either passed individually or aggregated into one variable containing a JSON array.
.. For individual variables pass any environment variables as necessary.
+
[source,sh]
----
guid=wkosp
ocp_username=wkulhane-redhat.com
jenkins_url=https://homework-jenkins-gpte-jenkins.apps.shared-na4.na4.openshift.opentlc.com
gitea_url=https://homework-gitea.apps.shared-na4.na4.openshift.opentlc.com
login_command='oc login -u wkulhane-redhat.com -p <Your OpenTLC password> https://api.shared-na4.na4.openshift.opentlc.com:8443'

oc new-app bookbag \
   --env guid="$guid" --env ocp_username="$ocp_username" \
   --env jenkins_url="$jenkins_url" --env gitea_url="$gitea_url" \
   --env login_command="${login_command}"
----

.. For aggregated JSON pass one variable *WORKSHOP_VARS* containing a JSON array of variables.
+
[source,sh]
----
WORKSHOP_VARS='{"guid": "wkosp", "ocp_username": "wkulhane-redhat.com", "jenkins_url": "https://homework-jenkins-gpte-jenkins.apps.shared-na4.na4.openshift.opentlc.com", "gitea_url": "https://homework-gitea.apps.shared-na4.na4.openshift.opentlc.com", "login_command": "oc login -u wkulhane-redhat.com -p <Your OpenTLC password> https://api.shared-na4.na4.openshift.opentlc.com:8443"}'

oc new-app bookbag --env WORKSHOP_VARS=${WORKSHOP_VARS}
----

. Expose the Route
+
[source,sh]
----
oc expose svc/bookbag
oc get route bookbag
----

. Access the documentation at the Route URL.
